import { motion, AnimatePresence } from "framer-motion"
import { useNavigate } from "react-router-dom"
import { useContext, useState } from "react"
import { ResumeContext } from "../context/ResumeContext"
import Footer from "../components/Footer"
import { KofiFloating } from "../components/KofiButton"

/* ---- Design tokens ---- */
const T = {
  bg: "#FAF8F5",
  surface: "#FFFFFF",
  text1: "#1A1410",
  text2: "#4A4540",
  text3: "#9C9690",
  accent: "#5C6B4E",
  accentSoft: "#EEF1EA",
  border: "rgba(26,20,16,0.08)",
  shadowSm: "0 1px 2px rgba(26,20,16,0.05)",
}

/* Only animation allowed: a 150ms opacity fade */
const fade = (delay = 0) => ({
  initial: { opacity: 0 },
  animate: { opacity: 1 },
  transition: { duration: 0.15, delay },
})

const fadeInView = (delay = 0) => ({
  initial: { opacity: 0 },
  whileInView: { opacity: 1 },
  viewport: { once: true },
  transition: { duration: 0.15, delay },
})

/* ---- Reusable styles ---- */
const cardStyle = {
  background: T.surface,
  border: `1px solid ${T.border}`,
  borderRadius: 14,
  padding: 24,
  boxShadow: T.shadowSm,
}

const btnBase = {
  height: 36,
  borderRadius: 10,
  padding: "0 18px",
  fontSize: 14,
  fontWeight: 600,
  fontFamily: "inherit",
  cursor: "pointer",
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 6,
  border: "1px solid transparent",
  transition: "opacity 150ms ease",
  whiteSpace: "nowrap",
}

const btnAccent = { ...btnBase, background: T.accent, color: "#fff" }
const btnGhost = { ...btnBase, background: "transparent", color: T.text2, border: `1px solid ${T.border}` }

const sectionLabel = {
  display: "inline-block",
  fontSize: 12,
  fontWeight: 700,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  color: T.accent,
  marginBottom: 14,
}

const features = [
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/>
      </svg>
    ),
    title: "ATS Score Analysis",
    desc: "Precise ATS compatibility prediction matched against any job description."
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
      </svg>
    ),
    title: "Semantic Matching",
    desc: "AI-powered alignment beyond simple keyword matching — understands meaning."
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
      </svg>
    ),
    title: "Keyword Detection",
    desc: "Finds exactly which keywords are missing and explains why they matter."
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
      </svg>
    ),
    title: "AI Suggestions",
    desc: "Actionable bullet rewrites and summary improvements generated by AI."
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
        <polyline points="14 2 14 8 20 8"/>
        <line x1="16" y1="13" x2="8" y2="13"/>
        <line x1="16" y1="17" x2="8" y2="17"/>
      </svg>
    ),
    title: "Resume Parsing",
    desc: "Deep structured extraction from PDF files — nothing gets missed."
  },
  {
    icon: (
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M9.5 2A2.5 2.5 0 0112 4.5v15a2.5 2.5 0 01-4.96-.46 2.5 2.5 0 01.01-3.04A2.5 2.5 0 019.5 2z"/>
        <path d="M14.5 2A2.5 2.5 0 0112 4.5v15a2.5 2.5 0 004.96-.46 2.5 2.5 0 00-.01-3.04A2.5 2.5 0 0114.5 2z"/>
      </svg>
    ),
    title: "JD Analysis",
    desc: "Deep analysis of job descriptions for higher matching accuracy."
  },
]

export default function Landing() {
  const navigate = useNavigate()
  const { setResumeFile, setJobDescription, jobDescription } = useContext(ResumeContext)
  const [file, setFile] = useState(null)
  const [error, setError] = useState("")
  const [jdOpen, setJdOpen] = useState(false)
  const [dragOver, setDragOver] = useState(false)

  const handleFile = (e) => {
    const f = e.target.files[0]
    if (!f) return
    const allowed = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
    if (!allowed.includes(f.type)) { setError("Only PDF and DOCX allowed"); return }
    setFile(f); setResumeFile(f); setError("")
  }

  const handleDrop = (e) => {
    e.preventDefault(); setDragOver(false)
    const f = e.dataTransfer.files[0]
    if (f) handleFile({ target: { files: [f] } })
  }

  const handleGuestAnalyze = () => {
    if (!file) { setError("Upload your resume first"); return }
    if (!jobDescription.trim()) { setError("Paste a job description"); return }
    navigate("/guest-loading")
  }

  return (
    <div style={{ background: T.bg, color: T.text1, minHeight: "100vh", fontFamily: "Inter, sans-serif" }}>

      {/* Nav — full width top bar, 56px, border-bottom */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 50,
        background: T.surface,
        borderBottom: `1px solid ${T.border}`,
        height: 56,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0 clamp(20px,5vw,40px)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{
            width: 30, height: 30, background: T.accent, borderRadius: 8,
            display: "flex", alignItems: "center", justifyContent: "center"
          }}>
            <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/>
            </svg>
          </div>
          <span style={{ fontWeight: 700, fontSize: 17, letterSpacing: "-0.02em", color: T.text1 }}>
            Resume<span style={{ color: T.accent }}>AI</span>
          </span>
        </div>
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <button style={btnGhost} onClick={() => navigate("/login")}>Sign In</button>
          <button style={btnAccent} onClick={() => navigate("/signup")}>Get Started</button>
        </div>
      </nav>

      {/* Hero */}
      <section style={{
        maxWidth: 880, margin: "0 auto",
        padding: "clamp(72px,11vw,128px) clamp(20px,5vw,32px) 80px",
        textAlign: "center",
        display: "flex", flexDirection: "column", alignItems: "center",
      }}>
        <motion.div {...fade(0)}>
          <span style={{
            display: "inline-flex", alignItems: "center", gap: 7,
            background: T.accentSoft, color: T.accent,
            fontSize: 12, fontWeight: 600, padding: "6px 14px",
            borderRadius: 8, letterSpacing: "0.02em",
            border: `1px solid ${T.border}`, marginBottom: 32,
          }}>
            <span style={{ width: 6, height: 6, borderRadius: "50%", background: T.accent }} />
            AI-Powered Resume Analysis
          </span>
        </motion.div>

        <motion.h1 {...fade(0.05)} style={{
          fontSize: "clamp(40px,6vw,64px)", fontWeight: 800,
          lineHeight: 1.05, letterSpacing: "-0.04em", marginBottom: 24,
          color: T.text1, maxWidth: 760,
        }}>
          Get hired faster with{" "}
          <span style={{ color: T.accent }}>smarter resume analysis</span>
        </motion.h1>

        <motion.p {...fade(0.1)} style={{
          fontSize: 17, color: T.text2,
          lineHeight: 1.6, maxWidth: 540, margin: "0 auto 36px", fontWeight: 400
        }}>
          Analyze ATS compatibility, skill alignment, and keyword gaps in seconds.
          Built for job seekers who want real results.
        </motion.p>

        <motion.div {...fade(0.15)} style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
          <button style={btnAccent} onClick={() => navigate("/signup")}>
            Sign Up Free
          </button>
          <button
            style={btnGhost}
            onClick={() => document.getElementById("try-free").scrollIntoView({ behavior: "smooth" })}
          >
            Try Without Signup →
          </button>
        </motion.div>

        <motion.div {...fade(0.2)} style={{ display: "flex", gap: 28, justifyContent: "center", marginTop: 40, flexWrap: "wrap" }}>
          {["ATS Optimized", "Instant Results", "No Credit Card"].map(t => (
            <span key={t} style={{ display: "flex", alignItems: "center", gap: 7, fontSize: 13, color: T.text3, fontWeight: 500 }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={T.accent} strokeWidth="2.5">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
              {t}
            </span>
          ))}
        </motion.div>
      </section>

      {/* Social proof strip */}
      <motion.div
        {...fadeInView()}
        style={{ maxWidth: 880, margin: "0 auto 88px", padding: "0 clamp(20px,5vw,32px)" }}
      >
        <div style={{
          display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16
        }}>
          {[
            { num: "2x", label: "More Interview Callbacks" },
            { num: "< 5s", label: "Instant Resume Feedback" },
            { num: "500+", label: "Active Job Seekers" },
          ].map(s => (
            <div key={s.label} style={{ ...cardStyle, textAlign: "center" }}>
              <p style={{ fontSize: "clamp(28px,4vw,36px)", fontWeight: 800, color: T.text1, letterSpacing: "-0.03em", marginBottom: 6 }}>{s.num}</p>
              <p style={{ fontSize: 13, color: T.text3, lineHeight: 1.4, fontWeight: 500 }}>{s.label}</p>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Free Trial */}
      <section id="try-free" style={{ maxWidth: 920, margin: "0 auto 104px", padding: "0 clamp(16px,4vw,24px)" }}>
        <motion.div {...fadeInView()} style={{ ...cardStyle, padding: "clamp(28px,5vw,48px)" }}>
          <div style={{ textAlign: "center", marginBottom: 32 }}>
            <span style={sectionLabel}>Free Trial</span>
            <h2 style={{ fontSize: "clamp(24px,4vw,32px)", fontWeight: 800, letterSpacing: "-0.03em", marginBottom: 10, color: T.text1 }}>
              Try it now — no signup needed
            </h2>
            <p style={{ color: T.text3, fontSize: 14, lineHeight: 1.6, maxWidth: 460, margin: "0 auto" }}>
              Get your ATS score and keyword match instantly. Sign up to unlock full AI suggestions.
            </p>
          </div>

          {error && (
            <div style={{
              background: "#FDECEC", border: "1px solid #F5C2C2",
              color: "#B42318", borderRadius: 10,
              padding: "10px 16px", fontSize: 13, marginBottom: 24, textAlign: "center"
            }}>
              {error}
            </div>
          )}

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 16, marginBottom: 28 }}>
            {/* Upload */}
            <div
              onDragOver={e => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              style={{
                border: `1px ${dragOver ? "solid" : "dashed"} ${dragOver ? T.accent : T.border}`,
                background: dragOver ? T.accentSoft : T.bg,
                borderRadius: 14, padding: "32px 24px",
                display: "flex", flexDirection: "column", alignItems: "center",
                justifyContent: "center", textAlign: "center", minHeight: 224,
              }}
            >
              <div style={{
                width: 44, height: 44, background: T.accentSoft,
                borderRadius: 10, display: "flex", alignItems: "center",
                justifyContent: "center", marginBottom: 16, color: T.accent,
                border: `1px solid ${T.border}`
              }}>
                <svg width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.8" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/>
                </svg>
              </div>
              <p style={{ fontWeight: 700, fontSize: 14, marginBottom: 4, color: T.text1 }}>Upload Resume</p>
              <p style={{ fontSize: 12.5, color: T.text3, marginBottom: 18 }}>PDF or DOCX · drag & drop</p>
              <label style={{ ...btnAccent, cursor: "pointer" }}>
                Choose File
                <input type="file" accept=".pdf,.docx" style={{ display: "none" }} onChange={handleFile} />
              </label>
              {file && (
                <motion.div
                  {...fade(0)}
                  style={{
                    marginTop: 14, background: T.accentSoft,
                    border: `1px solid ${T.border}`, borderRadius: 8,
                    padding: "6px 12px", fontSize: 12, color: T.accent,
                    display: "flex", alignItems: "center", gap: 6, maxWidth: "100%", wordBreak: "break-all"
                  }}
                >
                  <svg width="12" height="12" fill={T.accent} viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/>
                  </svg>
                  {file.name}
                </motion.div>
              )}
            </div>

            {/* JD */}
            <div
              onClick={() => setJdOpen(true)}
              style={{
                border: `1px solid ${jobDescription ? T.accent : T.border}`,
                borderRadius: 14, padding: 24,
                display: "flex", flexDirection: "column", minHeight: 224,
                cursor: "pointer", background: T.bg,
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
                <p style={{ fontWeight: 700, fontSize: 14, color: T.text1 }}>Job Description</p>
                <span style={{
                  fontSize: 11.5, fontWeight: 600, padding: "3px 10px", borderRadius: 8,
                  background: jobDescription ? T.accent : T.accentSoft,
                  color: jobDescription ? "#fff" : T.accent,
                }}>
                  {jobDescription ? "✓ Added" : "Click to add"}
                </span>
              </div>
              <div className="custom-scrollbar" style={{ flex: 1, overflowY: "auto", maxHeight: 120 }}>
                {jobDescription
                  ? <p style={{ fontSize: 13, color: T.text2, lineHeight: 1.6, whiteSpace: "pre-wrap", margin: 0 }}>{jobDescription}</p>
                  : <p style={{ fontSize: 13, color: T.text3, margin: 0 }}>Paste the full job description for best results...</p>
                }
              </div>
              <p style={{ fontSize: 11.5, color: T.text3, textAlign: "right", marginTop: 12 }}>{jobDescription.length} characters</p>
            </div>
          </div>

          <div style={{ display: "flex", justifyContent: "center" }}>
            <button style={{ ...btnAccent, padding: "0 32px" }} onClick={handleGuestAnalyze}>
              Analyze Free →
            </button>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section style={{ maxWidth: 1120, margin: "0 auto 104px", padding: "0 clamp(16px,4vw,24px)" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <span style={sectionLabel}>Features</span>
          <h2 style={{ fontSize: "clamp(26px,4vw,38px)", fontWeight: 800, letterSpacing: "-0.03em", color: T.text1 }}>
            Everything you need to land the role
          </h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: 16 }}>
          {features.map((f, i) => (
            <motion.div key={f.title} {...fadeInView(Math.min(i * 0.03, 0.12))} style={cardStyle}>
              <div style={{
                width: 40, height: 40, background: T.accentSoft,
                borderRadius: 10, display: "flex", alignItems: "center",
                justifyContent: "center", color: T.accent, marginBottom: 16,
                border: `1px solid ${T.border}`
              }}>
                {f.icon}
              </div>
              <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 8, color: T.text1, letterSpacing: "-0.01em" }}>{f.title}</h3>
              <p style={{ fontSize: 13.5, color: T.text3, lineHeight: 1.6 }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section style={{ maxWidth: 920, margin: "0 auto 104px", padding: "0 clamp(16px,4vw,24px)" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <span style={sectionLabel}>How it works</span>
          <h2 style={{ fontSize: "clamp(24px,4vw,36px)", fontWeight: 800, letterSpacing: "-0.03em", color: T.text1 }}>
            From resume to interview in 3 steps
          </h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 16 }}>
          {[
            { step: "01", title: "Upload your resume", desc: "Drop your PDF or DOCX. We parse it instantly with no data stored without your consent." },
            { step: "02", title: "Paste the job description", desc: "Copy the full job posting. The more detail, the more precise the keyword and semantic match." },
            { step: "03", title: "Get your ATS report", desc: "See your match score, missing keywords, AI-rewritten bullets, and exactly what to fix." },
          ].map(s => (
            <div key={s.step} style={cardStyle}>
              <p style={{ fontSize: 12, fontWeight: 800, color: T.accent, letterSpacing: "0.08em", marginBottom: 14 }}>{s.step}</p>
              <h3 style={{ fontSize: 16, fontWeight: 700, color: T.text1, marginBottom: 10, letterSpacing: "-0.01em" }}>{s.title}</h3>
              <p style={{ fontSize: 13.5, color: T.text3, lineHeight: 1.6 }}>{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{ maxWidth: 720, margin: "0 auto 104px", padding: "0 clamp(16px,4vw,24px)", textAlign: "center" }}>
        <motion.div
          {...fadeInView()}
          style={{
            background: T.text1, borderRadius: 14,
            padding: "clamp(40px,7vw,60px) clamp(28px,5vw,52px)",
            boxShadow: T.shadowSm,
          }}
        >
          <h2 style={{ fontSize: "clamp(26px,4vw,36px)", fontWeight: 800, letterSpacing: "-0.03em", marginBottom: 14, color: "#fff" }}>
            Ready to beat the ATS?
          </h2>
          <p style={{ color: "rgba(255,255,255,0.6)", marginBottom: 32, fontSize: 16, lineHeight: 1.6 }}>
            Join students and professionals who use ResumeAI to land more interviews.
          </p>
          <div style={{ display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
            <button style={btnAccent} onClick={() => navigate("/signup")}>
              Get Started Free
            </button>
            <button
              style={{
                ...btnBase,
                background: "rgba(255,255,255,0.1)",
                color: "#fff",
                border: "1px solid rgba(255,255,255,0.18)",
              }}
              onClick={() => document.getElementById("try-free").scrollIntoView({ behavior: "smooth" })}
            >
              Try it free →
            </button>
          </div>
        </motion.div>
      </section>

      <Footer />
      <KofiFloating />

      {/* JD Modal */}
      <AnimatePresence>
        {jdOpen && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            style={{
              position: "fixed", top: 0, left: 0, right: 0, bottom: 0, zIndex: 50,
              display: "flex", alignItems: "center", justifyContent: "center",
              padding: 16, background: "rgba(26,20,16,0.45)",
            }}
            onClick={e => { if (e.target === e.currentTarget) setJdOpen(false) }}
          >
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              transition={{ duration: 0.15 }}
              style={{
                background: T.surface, width: "100%", maxWidth: 640,
                borderRadius: 14, maxHeight: "88vh",
                border: `1px solid ${T.border}`, boxShadow: "0 12px 32px rgba(26,20,16,0.16)",
                display: "flex", flexDirection: "column"
              }}
            >
              <div style={{
                display: "flex", justifyContent: "space-between", alignItems: "flex-start",
                padding: "22px 24px 14px"
              }}>
                <div>
                  <h3 style={{ fontSize: 17, fontWeight: 700, color: T.text1, letterSpacing: "-0.01em" }}>Job Description</h3>
                  <p style={{ fontSize: 12.5, color: T.text3, marginTop: 4 }}>Paste the complete job posting for best results</p>
                </div>
                <button
                  onClick={() => setJdOpen(false)}
                  style={{
                    width: 34, height: 34, borderRadius: 10,
                    background: T.bg, border: `1px solid ${T.border}`,
                    display: "flex", alignItems: "center", justifyContent: "center",
                    color: T.text3, cursor: "pointer", transition: "opacity 150ms ease", flexShrink: 0
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M18 6L6 18M6 6l12 12"/></svg>
                </button>
              </div>
              <div style={{ padding: "0 24px", flex: 1, overflow: "hidden" }}>
                <textarea
                  value={jobDescription}
                  onChange={e => setJobDescription(e.target.value)}
                  autoFocus
                  placeholder="Paste the full job description here — requirements, responsibilities, qualifications..."
                  style={{
                    width: "100%", height: "100%", minHeight: 300,
                    border: "none", outline: "none", resize: "none",
                    fontSize: 14, color: T.text1, lineHeight: 1.7,
                    fontFamily: "Inter, sans-serif", background: "transparent"
                  }}
                />
              </div>
              <div style={{
                display: "flex", justifyContent: "space-between", alignItems: "center",
                padding: "14px 24px", borderTop: `1px solid ${T.border}`
              }}>
                <span style={{ fontSize: 12.5, color: T.text3 }}>{jobDescription.length} characters</span>
                <div style={{ display: "flex", gap: 8 }}>
                  {jobDescription.length > 0 && (
                    <button style={btnGhost} onClick={() => setJobDescription("")}>Clear</button>
                  )}
                  <button style={btnAccent} onClick={() => setJdOpen(false)}>Done ✓</button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
