import { motion, AnimatePresence } from "framer-motion"
import { useNavigate } from "react-router-dom"
import { useContext, useState } from "react"
import { ResumeContext } from "../context/ResumeContext"

const ease = [0.16, 1, 0.3, 1]

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.55, delay, ease }
})

const features = [
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/>
      </svg>
    ),
    title: "ATS Score Analysis",
    desc: "Precise ATS compatibility prediction matched against any job description."
  },
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M9.5 2A2.5 2.5 0 0112 4.5v15a2.5 2.5 0 01-4.96-.46 2.5 2.5 0 01.01-3.04A2.5 2.5 0 019.5 2z"/>
        <path d="M14.5 2A2.5 2.5 0 0112 4.5v15a2.5 2.5 0 004.96-.46 2.5 2.5 0 00-.01-3.04A2.5 2.5 0 0014.5 2z"/>
      </svg>
    ),
    title: "Semantic Matching",
    desc: "AI-powered alignment beyond simple keyword matching — understands meaning."
  },
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
      </svg>
    ),
    title: "Keyword Detection",
    desc: "Finds exactly which keywords are missing and explains why they matter."
  },
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>
      </svg>
    ),
    title: "AI Suggestions",
    desc: "Actionable bullet rewrites and summary improvements generated by AI."
  },
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/>
        <line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>
      </svg>
    ),
    title: "Resume Parsing",
    desc: "Deep structured extraction from PDF files — nothing gets missed."
  },
  {
    icon: (
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
      </svg>
    ),
    title: "JD Analysis",
    desc: "Deep analysis of job descriptions for higher matching accuracy."
  },
]

export default function Landing() {
  const navigate = useNavigate()
  const { setResumeFile, setJobDescription, jobDescription } = useContext(ResumeContext)
  const [file, setFile] = useState(null)
  const [error, setError] = useState("")
  const [jdOpen, setJdOpen] = useState(false)
  const [dragOver, setDragOver] = useState(false)

  const handleFile = (e) => {
    const f = e.target.files[0]
    if (!f) return
    const allowed = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
    if (!allowed.includes(f.type)) { setError("Only PDF and DOCX allowed"); return }
    setFile(f); setResumeFile(f); setError("")
  }

  const handleGuestAnalyze = () => {
    if (!file) { setError("Please upload your resume"); return }
    if (!jobDescription.trim()) { setError("Please paste a job description"); return }
    navigate("/guest-loading")
  }

  return (
    <div style={{ background: "var(--bg)", color: "var(--text-1)", minHeight: "100vh" }}>

      {/* Nav */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 50,
        background: "rgba(250,248,245,0.92)", backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        borderBottom: "1px solid var(--border)",
        padding: "0 clamp(20px, 5vw, 56px)", height: 60,
        display: "flex", alignItems: "center", justifyContent: "space-between"
      }}>
        <span style={{ fontWeight: 800, fontSize: 19, letterSpacing: "-0.6px", color: "var(--text-1)" }}>
          Resume<span style={{ color: "var(--accent)" }}>AI</span>
        </span>
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <button className="btn-ghost" style={{ padding: "8px 16px", fontSize: 13 }} onClick={() => navigate("/login")}>Sign In</button>
          <button className="btn-primary" style={{ padding: "8px 16px", fontSize: 13 }} onClick={() => navigate("/signup")}>Get Started</button>
        </div>
      </nav>

      {/* Hero */}
      <section style={{ maxWidth: 780, margin: "0 auto", padding: "clamp(60px, 10vw, 100px) clamp(20px, 5vw, 32px) 64px", textAlign: "center" }}>
        <motion.div {...fadeUp(0)}>
          <span className="badge badge-accent" style={{ marginBottom: 28, display: "inline-flex", padding: "5px 14px", fontSize: 12 }}>
            ✦ AI-Powered Resume Analysis
          </span>
        </motion.div>

        <motion.h1 {...fadeUp(0.08)} style={{
          fontSize: "clamp(36px, 6.5vw, 62px)", fontWeight: 800,
          lineHeight: 1.08, letterSpacing: "-2px", marginBottom: 22,
          color: "var(--text-1)"
        }}>
          Get hired faster with<br />
          <span style={{ color: "var(--accent)" }}>smarter resume analysis</span>
        </motion.h1>

        <motion.p {...fadeUp(0.15)} style={{
          fontSize: "clamp(15px, 2vw, 17px)", color: "var(--text-2)",
          lineHeight: 1.75, maxWidth: 500, margin: "0 auto 36px", fontWeight: 400
        }}>
          Analyze ATS compatibility, skill alignment, and keyword gaps — in seconds. Built for job seekers who want real results.
        </motion.p>

        <motion.div {...fadeUp(0.22)} style={{ display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
          <button className="btn-primary" style={{ padding: "13px 28px", fontSize: 14 }} onClick={() => navigate("/signup")}>
            Sign Up Free
          </button>
          <button className="btn-ghost" style={{ padding: "13px 24px", fontSize: 14 }} onClick={() => document.getElementById("try-free").scrollIntoView({ behavior: "smooth" })}>
            Try Without Signup →
          </button>
        </motion.div>

        <motion.div {...fadeUp(0.3)} style={{ display: "flex", gap: 24, justifyContent: "center", marginTop: 40, flexWrap: "wrap" }}>
          {["ATS Optimized", "Instant Results", "No Credit Card"].map((t) => (
            <span key={t} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "var(--text-3)", fontWeight: 500 }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>
              {t}
            </span>
          ))}
        </motion.div>
      </section>

      {/* Free Trial */}
      <section id="try-free" style={{ maxWidth: 860, margin: "0 auto 80px", padding: "0 clamp(16px, 4vw, 24px)" }}>
        <motion.div
          initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }} transition={{ duration: 0.55, ease }}
          className="card" style={{ padding: "clamp(28px, 5vw, 44px)" }}
        >
          <div style={{ textAlign: "center", marginBottom: 32 }}>
            <span className="section-label">Free Trial</span>
            <h2 style={{ fontSize: "clamp(22px, 4vw, 28px)", fontWeight: 800, letterSpacing: "-0.8px", marginBottom: 8, color: "var(--text-1)" }}>
              Try it now — no signup needed
            </h2>
            <p style={{ color: "var(--text-3)", fontSize: 14, lineHeight: 1.6 }}>
              Get your ATS score and keyword match instantly. Sign up to unlock full AI suggestions.
            </p>
          </div>

          {error && (
            <div style={{ background: "var(--danger-bg)", border: "1px solid var(--danger-bd)", color: "var(--danger)", borderRadius: "var(--r-sm)", padding: "10px 16px", fontSize: 13, marginBottom: 20 }}>
              {error}
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            {/* Upload box */}
            <div
              style={{
                border: `1.5px dashed ${dragOver ? "var(--accent)" : "var(--border-2)"}`,
                background: dragOver ? "var(--accent-soft)" : "var(--surface)",
                borderRadius: "var(--r-md)", padding: 28,
                display: "flex", flexDirection: "column", alignItems: "center",
                justifyContent: "center", textAlign: "center", minHeight: 200,
                transition: "border-color 0.18s, background 0.18s"
              }}
              onDragOver={e => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={e => { e.preventDefault(); setDragOver(false); const f = e.dataTransfer.files[0]; if (f) handleFile({ target: { files: [f] } }) }}
            >
              <div style={{ width: 46, height: 46, background: "var(--accent-soft)", borderRadius: "var(--r-sm)", display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 14, color: "var(--accent)" }}>
                <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.8" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" /></svg>
              </div>
              <p style={{ fontWeight: 700, fontSize: 14, marginBottom: 4, color: "var(--text-1)" }}>Upload Resume</p>
              <p style={{ fontSize: 12, color: "var(--text-3)", marginBottom: 16 }}>PDF or DOCX · drag & drop</p>
              <label className="btn-primary" style={{ padding: "8px 18px", fontSize: 12, cursor: "pointer" }}>
                Choose File
                <input type="file" accept=".pdf,.docx" style={{ display: "none" }} onChange={handleFile} />
              </label>
              {file && (
                <motion.div initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
                  style={{ marginTop: 12, background: "var(--success-bg)", border: "1px solid var(--success-bd)", borderRadius: "var(--r-xs)", padding: "6px 12px", fontSize: 12, color: "#166534", maxWidth: "100%", wordBreak: "break-all", display: "flex", alignItems: "center", gap: 6 }}
                >
                  <svg width="11" height="11" fill="#16A34A" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/></svg>
                  {file.name}
                </motion.div>
              )}
            </div>

            {/* JD card */}
            <div
              onClick={() => setJdOpen(true)}
              style={{ border: "1.5px solid var(--border)", borderRadius: "var(--r-md)", padding: 20, display: "flex", flexDirection: "column", minHeight: 200, cursor: "pointer", background: "var(--surface)", transition: "border-color 0.18s, box-shadow 0.18s" }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = "var(--accent)"; e.currentTarget.style.boxShadow = "var(--shadow-md)" }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = "var(--border)"; e.currentTarget.style.boxShadow = "none" }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
                <p style={{ fontWeight: 700, fontSize: 14, color: "var(--text-1)" }}>Job Description</p>
                <span className="badge badge-accent" style={{ fontSize: 11, padding: "3px 8px" }}>
                  {jobDescription ? "✓ Added" : "Click to add"}
                </span>
              </div>
              <div className="custom-scrollbar" style={{ flex: 1, overflowY: "auto", maxHeight: 110, paddingRight: 4 }}>
                {jobDescription ? (
                  <p style={{ fontSize: 13, color: "var(--text-2)", lineHeight: 1.65, whiteSpace: "pre-wrap", margin: 0 }}>{jobDescription}</p>
                ) : (
                  <p style={{ fontSize: 13, color: "var(--text-3)", margin: 0 }}>Paste the full job description for best results...</p>
                )}
              </div>
              <p style={{ fontSize: 11, color: "var(--text-3)", textAlign: "right", marginTop: 10 }}>{jobDescription.length} characters</p>
            </div>
          </div>

          <div style={{ display: "flex", justifyContent: "center" }}>
            <motion.button whileTap={{ scale: 0.97 }} className="btn-primary" style={{ padding: "13px 40px", fontSize: 14 }} onClick={handleGuestAnalyze}>
              Analyze Free →
            </motion.button>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section style={{ maxWidth: 1100, margin: "0 auto 80px", padding: "0 clamp(16px, 4vw, 24px)" }}>
        <div style={{ textAlign: "center", marginBottom: 48 }}>
          <span className="section-label">Features</span>
          <h2 style={{ fontSize: "clamp(24px, 4vw, 36px)", fontWeight: 800, letterSpacing: "-0.8px", color: "var(--text-1)" }}>
            Everything you need to land the role
          </h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(290px, 1fr))", gap: 16 }}>
          {features.map((f, i) => (
            <motion.div
              key={f.title} className="card"
              initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.45, delay: i * 0.05, ease }}
              whileHover={{ y: -3, boxShadow: "var(--shadow-md)" }}
              style={{ padding: "28px 28px 24px" }}
            >
              <div style={{ width: 42, height: 42, background: "var(--accent-soft)", borderRadius: "var(--r-sm)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--accent)", marginBottom: 16, border: "1px solid var(--accent-mid)" }}>
                {f.icon}
              </div>
              <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 6, color: "var(--text-1)", letterSpacing: "-0.2px" }}>{f.title}</h3>
              <p style={{ fontSize: 13, color: "var(--text-3)", lineHeight: 1.65 }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{ maxWidth: 640, margin: "0 auto 80px", padding: "0 clamp(16px, 4vw, 24px)", textAlign: "center" }}>
        <motion.div
          initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }} transition={{ duration: 0.5, ease }}
          style={{
            background: "var(--accent-soft)",
            border: "1px solid var(--accent-mid)",
            borderRadius: "var(--r-xl)",
            padding: "clamp(36px, 6vw, 56px) clamp(28px, 5vw, 48px)"
          }}
        >
          <h2 style={{ fontSize: "clamp(24px, 4vw, 32px)", fontWeight: 800, letterSpacing: "-0.8px", marginBottom: 12, color: "var(--text-1)" }}>
            Ready to beat the ATS?
          </h2>
          <p style={{ color: "var(--text-2)", marginBottom: 28, fontSize: 15, lineHeight: 1.65 }}>
            Join students and professionals who use ResumeAI to land more interviews.
          </p>
          <button className="btn-primary" style={{ padding: "13px 32px", fontSize: 14 }} onClick={() => navigate("/signup")}>
            Get Started Free
          </button>
        </motion.div>
      </section>

      {/* Footer */}
      <footer style={{ borderTop: "1px solid var(--border)", padding: "20px clamp(20px, 5vw, 56px)", display: "flex", justifyContent: "space-between", alignItems: "center", color: "var(--text-3)", fontSize: 13, flexWrap: "wrap", gap: 10 }}>
        <span style={{ fontWeight: 800, fontSize: 15, letterSpacing: "-0.4px", color: "var(--text-1)" }}>
          Resume<span style={{ color: "var(--accent)" }}>AI</span>
        </span>
        <span>Built for students and professionals</span>
      </footer>

      {/* JD Modal */}
      <AnimatePresence>
        {jdOpen && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            transition={{ duration: 0.18 }}
            className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-6"
            style={{ background: "rgba(26,22,17,0.5)", backdropFilter: "blur(6px)", WebkitBackdropFilter: "blur(6px)" }}
            onClick={e => { if (e.target === e.currentTarget) setJdOpen(false) }}
          >
            <motion.div
              initial={{ opacity: 0, y: 32 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 32 }}
              transition={{ type: "spring", stiffness: 320, damping: 32 }}
              style={{ background: "var(--surface)", width: "100%", maxWidth: 640, borderRadius: "20px 20px 0 0", maxHeight: "88vh", boxShadow: "0 -8px 40px rgba(0,0,0,0.12)", display: "flex", flexDirection: "column" }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 20px 12px" }}>
                <div>
                  <h3 style={{ fontSize: 17, fontWeight: 700, color: "var(--text-1)", letterSpacing: "-0.3px", margin: 0 }}>Job Description</h3>
                  <p style={{ fontSize: 12, color: "var(--text-3)", marginTop: 3 }}>Paste the complete job posting for best results</p>
                </div>
                <button onClick={() => setJdOpen(false)} style={{ width: 34, height: 34, borderRadius: "50%", background: "var(--bg)", border: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--text-3)", cursor: "pointer", transition: "background 0.15s" }}
                  onMouseEnter={e => e.currentTarget.style.background = "var(--bg-2)"}
                  onMouseLeave={e => e.currentTarget.style.background = "var(--bg)"}
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6L6 18M6 6l12 12"/></svg>
                </button>
              </div>
              <div style={{ padding: "0 20px", flex: 1, overflow: "hidden" }}>
                <textarea
                  autoFocus value={jobDescription}
                  onChange={e => setJobDescription(e.target.value)}
                  placeholder="Paste the full job description here — requirements, responsibilities, qualifications..."
                  style={{ width: "100%", height: "100%", minHeight: 280, border: "none", outline: "none", resize: "none", fontSize: 14, color: "var(--text-1)", lineHeight: 1.7, fontFamily: "Inter, sans-serif", background: "transparent" }}
                />
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 20px", borderTop: "1px solid var(--border)" }}>
                <span style={{ fontSize: 12, color: "var(--text-3)" }}>{jobDescription.length} characters</span>
                <div style={{ display: "flex", gap: 8 }}>
                  {jobDescription.length > 0 && (
                    <button className="btn-ghost" style={{ padding: "7px 14px", fontSize: 12 }} onClick={() => setJobDescription("")}>Clear</button>
                  )}
                  <button className="btn-primary" style={{ padding: "8px 20px", fontSize: 13 }} onClick={() => setJdOpen(false)}>Done ✓</button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}